print("Hello, I am python learner")
print("Programming is my primary habit")
print("All day long I eat, sleep and code")
print("I am a student and like to study and build programs")
print("I like to eat italians Food")
print("This is version 4 in starter.py")
